[project]
name = "source-han-mapping-viewer"
version = "0.0.0"
requires-python = ">=3.14"

dependencies = [
    "httpx[http2]==0.28.1",
    "tqdm==4.67.1",
    "fonttools[woff]==4.61.1",
    "unidata-blocks==0.0.24",
    "character-encoding-utils==0.0.12",
    "loguru==0.7.3",
]
